# Generated by Django 3.0.6 on 2020-06-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200601_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='img',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
