# Generated by Django 3.0.6 on 2020-06-01 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200601_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='img',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
