# Generated by Django 3.0.6 on 2020-06-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200601_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='template',
            field=models.CharField(default='D&D', max_length=10),
        ),
        migrations.AddField(
            model_name='charactersheet',
            name='other_personal',
            field=models.ManyToManyField(to='api.PersonalData'),
        ),
    ]
