# Generated by Django 3.0.6 on 2020-06-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200609_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charactersheet',
            name='other_personal',
            field=models.ManyToManyField(null=True, to='api.PersonalData'),
        ),
    ]
